/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.androidsoft.games.puzzle.kids;

public final class R {
    public static final class anim {
        public static final int fade=0x7f040000;
        public static final int layout_random_fade=0x7f040001;
    }
    public static final class array {
        public static final int credits=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int empty_tile=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int item_1=0x7f020003;
        public static final int item_10=0x7f020004;
        public static final int item_11=0x7f020005;
        public static final int item_12=0x7f020006;
        public static final int item_13=0x7f020007;
        public static final int item_14=0x7f020008;
        public static final int item_15=0x7f020009;
        public static final int item_16=0x7f02000a;
        public static final int item_2=0x7f02000b;
        public static final int item_3=0x7f02000c;
        public static final int item_4=0x7f02000d;
        public static final int item_5=0x7f02000e;
        public static final int item_6=0x7f02000f;
        public static final int item_7=0x7f020010;
        public static final int item_8=0x7f020011;
        public static final int item_9=0x7f020012;
        public static final int second_logo=0x7f020013;
        public static final int splash=0x7f020014;
    }
    public static final class id {
        public static final int button_play=0x7f070004;
        public static final int container=0x7f070000;
        public static final int gameview=0x7f070006;
        public static final int gridview=0x7f070007;
        public static final int image_splash=0x7f070002;
        public static final int second_logo=0x7f070005;
        public static final int splash=0x7f070001;
        public static final int text=0x7f070003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int activity_title=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int button_play=0x7f060005;
        public static final int credits_app_name=0x7f060013;
        public static final int credits_current_version=0x7f060014;
        public static final int credits_menu=0x7f060012;
        public static final int message_1=0x7f060007;
        public static final int message_10=0x7f060010;
        public static final int message_11=0x7f060011;
        public static final int message_2=0x7f060008;
        public static final int message_3=0x7f060009;
        public static final int message_4=0x7f06000a;
        public static final int message_5=0x7f06000b;
        public static final int message_6=0x7f06000c;
        public static final int message_7=0x7f06000d;
        public static final int message_8=0x7f06000e;
        public static final int message_9=0x7f06000f;
        public static final int new_game=0x7f060003;
        public static final int quit=0x7f060004;
        public static final int success=0x7f060002;
        public static final int version=0x7f060006;
    }
}
